//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import i18n from '@dhis2/d2-i18n'

import enTranslations from './en/translations.json'

const namespace = 'default'

// Use 'deep' = true and 'overwrite' = false to add to, but not overwrite,
// custom translations from the datastore (added by the app adapter)

i18n.addResourceBundle('en', namespace, enTranslations, true, false)
i18n.addResourceBundle('en', namespace, enTranslations, true, false)

export default i18n
